### ISSUE TITLE
README suggestion: Add workflow overview figure

### ISSUE THREAD

**Issue by martinaryee** [aryeelab/hichipper#1]
Suggestion: Add workflow figure and/or description showing something like: Call peaks/anchors -> Map PETs to anchors -> Identify loops -> Calculate loop metrics (PET count, p-value)

**Comment by caleblareau** [comment]
Other things that need to be better documented:
- peak calling specification
- split samples (should be working, just need to make note)
- restriction fragment padding
- take highlights of supplement wrt modified peak calling and discuss

**Comment by caleblareau** [comment]
Lots of artwork but need to do specifically these things. It will be particularly useful for elucidating what happens when users supply their own peaks versus when they get called or not. It should be a vertical flow chart. Posting this comment to remind myself to do this later today.
