### ISSUE TITLE
chipseq input

### ISSUE THREAD

**Issue by sb5169** [aryeelab/hichipper#18]
Hi I had a question about setting up the yaml file.

If I have two conditions in my hic-pro output folder let's say WT and Mutant, how do I make sure the chipseq files I indicate in the yaml will match the correct output in the HiC-pro output folder.

i.e.

peaks:
  - chipseq/WT.bed 
  - chipseq/Mutant.bed 
resfrags:
  - /ifs/home/sb5169/hg38/MboI_resfrag_hg38.bed
hicpro_output:
  - /ifs/home/sb5169/PL_HiChIP2/Pooled_output

**Comment by caleblareau** [comment]
yeah good question. You can't do this in a single run. You'll want to create two `.yaml` files, each one specifying its own chip-seq, and then restrict the analysis to the sample you want using the `--keep-samples` or `--ignore-samples` flags. Does this make sense @sb5169 ?
