### ISSUE TITLE
About the *.filt.intra.loop_counts.bedpe format

### ISSUE THREAD

**Issue by lijiacd985** [aryeelab/hichipper#22]
Hi there,

I got the *.filt.intra.loop_counts.bedpe, but what the third column "1" mean ?
Is the third column mean PET number that support this loop? Should I filter again based on third column? How to filter?

How can I get the p/fdr value for each loop?

Thanks

Best

Jia Li

chr10,100015532,100016705	chr10,100118360,100119539	1
chr10,100015532,100016705	chr10,100129996,100131143	1
chr10,100015532,100016705	chr10,100153694,100154869	1
chr10,100027364,100028596	chr10,100038190,100039338	1
chr10,100032538,100033776	chr10,100038190,100039338	1
chr10,100032538,100033776	chr10,100068721,100069868	1
chr10,100032538,100033776	chr10,100180125,100181277	1
chr10,100032538,100033776	chr10,100603185,100604332	1
chr10,100038190,100039338	chr10,100168859,100170006	1
chr10,100038190,100039338	chr10,100431107,100432285	1

**Comment by caleblareau** [comment]
Hi @lijiacd985 -- the last column in the `.bedpe` files are the counts per interaction locus. Only the `.mango` files have the per-loop significance values. Alternatively, you can read these into `diffloop` to compute p/fdr values for multiple samples

https://bioconductor.org/packages/release/bioc/html/diffloop.html

**Comment by lijiacd985** [comment]
Hi,

Thanks for your reply. I just want to get the significant loops for each sample first. I have tried these several days, but I couldnot get the *.mango files. Even I used your tests files, as command: "hichipper --out output1  yaml/one.yaml --skip-resfrag-pad --skip-diffloop". 

Thanks

**Comment by caleblareau** [comment]
Yeah @lijiacd985 you have to let `diffloop` run to enable this. (just remove the `--skip-diffloop` flag). The example command that you have noted there is only applicable when you want to not use any pre-processing involving R (in case you don't have it installed on your machine)

**Comment by lijiacd985** [comment]
@caleblareau   OK. got you.  Thanks
