### ISSUE TITLE
empty interaction

### ISSUE THREAD

**Issue by lijiacd985** [aryeelab/hichipper#23]
Hi,
I used the following command (when use test folder it is ok with the output file)
hichipper --out TKO.loop  TKO.yaml --skip-resfrag-pad 
but for my samples, it output empty files (no error reports):
    0 Oct  3 20:04 fq.filt.intra.loop_counts.bedpe
    0 Oct  3 20:04 fq.inter.loop_counts.bedpe
    0 Oct  3 20:04 fq.intra.loop_counts.bedpe
  492 Oct  3 20:04 fq.stat
 2001 Oct  3 20:04 TKO.E12.loop.hichipper.log

log:
Tue Oct 03 19:17:21 CDT 2017: Starting hichipper pipeline v0.7.0
Tue Oct 03 19:17:21 CDT 2017: Parsing user parameters
Tue Oct  3 19:17:21 CDT 2017: Processing fq
Tue Oct  3 19:17:21 CDT 2017: Total_PETs=699057358
Tue Oct  3 19:19:28 CDT 2017: Mapped_unique_quality_pairs=565946889
Tue Oct  3 19:19:45 CDT 2017: Mapped_unique_quality_valid_pairs=167545325
Tue Oct  3 19:19:45 CDT 2017: Intersecting PETs with anchors
Tue Oct  3 19:19:45 CDT 2017: Finished the anchor merging.
Tue Oct  3 20:06:12 CDT 2017: Intrachromosomal_valid_small=0
Tue Oct  3 20:06:12 CDT 2017: Intrachromosomal_valid_med=0
Tue Oct  3 20:06:12 CDT 2017: Intrachromosomal_valid_large=0
Tue Oct  3 20:06:12 CDT 2017: Total number of anchors used: 164465
Tue Oct  3 20:06:12 CDT 2017: Total number of reads in anchors: 152747515
Tue Oct  3 20:06:12 CDT 2017: Mapped_unique_intra_quality_anchor=0
Tue Oct  3 20:06:12 CDT 2017: Mapped_unique_intra_quality_anchor_small=0
Tue Oct  3 20:06:12 CDT 2017: Mapped_unique_intra_quality_anchor_med=0
Tue Oct  3 20:06:12 CDT 2017: Mapped_unique_intra_quality_anchor_large=0
Tue Oct  3 20:06:12 CDT 2017: Loop_PETs=

Where is the problem?

Thanks

**Comment by caleblareau** [comment]
@lijiacd985 a bit hard to know from this, but it looks like your anchors have 0 overlaps with your interactions. Are you using an _a priori_ defined anchor set? Maybe check to verify that the chromosome names in the bed file are the same as the chromosome names in the HiC-Pro output? Also could you `cat fq.stat`?

**Comment by lijiacd985** [comment]
cat fq.stat:

Total_PETs=699057358
Mapped_unique_quality_pairs=565946889
Mapped_unique_quality_valid_pairs=167545325
Mapped_unique_quality_valid_intrachromosomal=0
Intrachromosomal_valid_small=0
Intrachromosomal_valid_med=0
Intrachromosomal_valid_large=0
Mapped_unique_intra_quality_anchor=0
Mapped_unique_intra_quality_anchor_small=0
Mapped_unique_intra_quality_anchor_med=0
Mapped_unique_intra_quality_anchor_large=0
Number_of_Anchors=164465
MIN_LENGTH=5000
MAX_LENGTH=2000000
READS_IN_ANCHORS=152747515

**Comment by caleblareau** [comment]
Okay so it looks like you have anchors called successfully but there are, apparently, zero intrachromosomal interactions. Could you verify that there is a `_allValidPairs` file and maybe show the `head` of it? Also, what version of HiC-Pro did you use? Did you run both step 1 and step 2?

**Comment by lijiacd985** [comment]
The version for HicPro is HiC-Pro_2.9.0.
Yes I finished the step1 and 2.

head *_allValidPairs:
NS500669:176:H3CMVBGX3:1:11204:5408:6307        chr1    3000229 -       chr1    48298207        -       133     HIC_chr1_2
NS500669:176:H3CMVBGX3:2:12302:0:0      chr1    3000229 -       chr1    120012493       +       132     HIC_chr1_2      HIC_c
NS500669:176:H3CMVBGX3:2:11209:0:0      chr1    3000239 -       chr4    17968101        -       176     HIC_chr1_2      HIC_c
NS500669:176:H3CMVBGX3:1:21201:21631:14182      chr1    3000244 -       chr1    23484731        +       124     HIC_chr1_2
NS500669:176:H3CMVBGX3:2:11312:0:0      chr1    3000244 -       chr4    28120603        -       170     HIC_chr1_2      HIC_c
NS500669:176:H3CMVBGX3:2:21103:0:0      chr1    3000252 -       chr5    104418868       -       218     HIC_chr1_2      HIC_c
NS500669:176:H3CMVBGX3:2:21102:0:0      chr1    3000269 -       chr4    12693217        +       160     HIC_chr1_2      HIC_c
NS500669:176:H3CMVBGX3:2:12206:0:0      chr1    3000269 -       chr4    105553764       +       185     HIC_chr1_2      HIC_c
NS500669:176:H3CMVBGX3:2:22203:0:0      chr1    3000269 -       chr6    143696951       -       191     HIC_chr1_2      HIC_c
NS500669:176:H3CMVBGX3:1:11207:5576:16810       chr1    3000286 -       chr1    18567161        -       159     HIC_chr1_2

**Comment by caleblareau** [comment]
yeah I don't think that I can tell from this; everything looks good. 

My only thought is to rerun it with the `--keep-temp-files` flag and then show me the file sizes (run `ls -lrth` ) in the resulting output folder and maybe we can see from that?

**Comment by lijiacd985** [comment]
I rerun and please check the following:

-rw-r--r-- 1 jiali sunlab  13M Oct  3 21:49 userSuppliedPeaks.bed.tmp
-rw-r--r-- 1 jiali sunlab 4.3M Oct  3 21:49 userSuppliedPeaks.bed.tmp_pad.bed.tmp
-rw-r--r-- 1 jiali sunlab 3.8M Oct  3 21:51 fq_temporary_peaks.merged.bed.tmp
-rw-r--r-- 1 jiali sunlab   18 Oct  3 22:31 fq.peakReads.tmp
-rw-r--r-- 1 jiali sunlab    0 Oct  3 22:31 fq_interactions.bedpe.tmp
-rw-r--r-- 1 jiali sunlab    0 Oct  3 22:38 fq_anchor1.bed.tmp
-rw-r--r-- 1 jiali sunlab    0 Oct  3 22:38 fq_anchor2.bed.tmp
-rw-r--r-- 1 jiali sunlab    0 Oct  3 22:38 fq_anchor.interactions.bedpe.tmp
-rw-r--r-- 1 jiali sunlab    0 Oct  3 22:38 fq.loop_counts.bedpe.tmp
-rw-r--r-- 1 jiali sunlab    0 Oct  3 22:38 fq.inter.loop_counts.bedpe
-rw-r--r-- 1 jiali sunlab    0 Oct  3 22:38 fq.intra.loop_counts.bedpe
-rw-r--r-- 1 jiali sunlab    0 Oct  3 22:38 fq.filt.intra.loop_counts.bedpe
-rw-r--r-- 1 jiali sunlab  492 Oct  3 22:38 fq.stat
-rw-rw-r-- 1 jiali sunlab 9.9K Oct  3 22:38 qcReport_make.Rmd
-rw-rw-r-- 1 jiali sunlab  442 Oct  3 22:38 qcReport.R
-rw-r--r-- 1 jiali sunlab 2.0K Oct  3 22:38 TKO.E12.loop2.hichipper.log

Thanks

**Comment by lijiacd985** [comment]
Hi @caleblareau ,

I think I know the problem. 

When hichipper calculate the interactions.bedpe.tmp, it need sort. Because my data is large, so there is no space left in tmp file when use "sort" function. I add "-T temp" in "sort" command and it solved. 

Maybe you can add "-T " option too, in case some users data is too large.

Thanks for all your help.

Best

Jia Li
