### ISSUE TITLE
Warning messages in QC report generation

### ISSUE THREAD

**Issue by 0xaf1f** [aryeelab/hichipper#25]
I installed hichipper on our cluster and ran the example as follows:

```
cp -r /path/to/hichipper/tests .
cd tests
hichipper --out output1 yaml/one.yaml
```
and the run appears to complete successfully, but the last thing printed is this:

```
Output created: output1.hichipper.qcreport.html
Warning messages:
1: Transformation introduced infinite values in continuous x-axis
2: Removed 13419 rows containing non-finite values (stat_bin).
Processing: d1
```
Is that an expected/ignorable warning for this example run?

**Comment by caleblareau** [comment]
Hi @0xaf1f -- Yes the warning messages are just that-- warnings. These are coming from drawing the histogram of the loop length values, and are expected. I'll leave this as a reminder to suppress these warning  messages in future updates

**Comment by caleblareau** [comment]
These are now supressed in `v0.7.1`
