### ISSUE TITLE
Rscript requirementsInstall.R fails with error in install.packages

### ISSUE THREAD

**Issue by sowmyaiyer** [aryeelab/hichipper#32]
Error:
```
Error in contrib.url(repos, type) :
  trying to use CRAN without setting a mirror
Calls: install_pkgs -> install.packages -> grep -> contrib.url
Execution halted
```
Fix: Added the parameter "repos" to install.packages on line 3
`if (length(new.pkg)) install.packages(new.pkg, dependencies = TRUE, repos="https://cloud.r-project.org")`

**Comment by caleblareau** [comment]
great, I see no reason why this wouldn't work. Implemented in new commit. Thanks!
