### ISSUE TITLE
If there any output file about peak calling

### ISSUE THREAD

**Issue by werhoog** [aryeelab/hichipper#33]
Hi， I have use this software  well . However , I can't  find any files out abut peaks since I use .bam file to call peak with MACS2.
Can I obtain it by some extra parameter?

**Comment by caleblareau** [comment]
Yes, you can retain these using the `--keep-temp-files` flag. I may try to make this more clean though.

**Comment by caleblareau** [comment]
@werhoog in the newest version of hichipper `v0.7.2` (just pushed to PyPi), a `{SAMPLE}.anchors.bed` file is now output per-sample as a default. 

also requested by @sowmyaiyer
