### ISSUE TITLE
About output file of *****.gz.txt

### ISSUE THREAD

**Issue by werhoog** [aryeelab/hichipper#36]
Hi, I met a new problem.So sorry to bother you many times.
This time, I am confused about *****.gz.txt which can be loaded to UCSC.However,I cant't see the interaction but a single line of each PET(there is no line between PETs).
And the file is about ：for example:
chr1	193775080	193780032	chr1:193403318-193409437,9	289586	.
Is that means PET "chr1	193775080	193780032" and PET "chr1:193403318-193409437" are interacted.And what "9" and "289586" means?
Thank you!

**Comment by caleblareau** [comment]
See specifications of the format here: http://wiki.wubrowse.org/Long-range <http://wiki.wubrowse.org/Long-range>

**Comment by werhoog** [comment]
Thank you.But I still failed to load UCSC(there are only single PETs without any interaction show between them(as usual, there is a line between them).And this software call loop with Anchors to  Anchors(which come from peaks).However,for HiChip, it is better to call loop with peak to all(otherwise peak to peak).
Am I right?
