### ISSUE TITLE
Error in { : task 1 failed - "need at least four unique 'x' values"

### ISSUE THREAD

**Issue by cjt5** [aryeelab/hichipper#37]
Hi, I am having an issue using hichipper regarding a specific anchor configuration. Interestingly, this only occurs when I am running hichipper using EACH,SELF to identify % in Loops. Using the same dataset, everything runs completely fine when supplying my own anchors from a separate ChIP-seq experiment, as well as calling peaks internally using COMBINED,ALL/COMBINED-SELF/EACH,ALL. The EACH,SELF command still runs and gives an output, but this results in extremely low peak calling in one of the samples, whereas all the other methods identify high % in Loops. The output from the error is attached below:

hichipper --out Control_HDAC_SMC3_HiChIPPeaks_EACH-SELF HiChIPPer.yaml 
Thu Apr 19 12:18:40 CDT 2018: Starting hichipper pipeline v0.7.1
Thu Apr 19 12:18:40 CDT 2018: Parsing user parameters
Thu Apr 19 12:19:29 CDT 2018: Performing hichipper-modified background peak calling
Read 7227576 rows and 6 (of 6) columns from 0.297 GB file in 00:00:09
Thu Apr 19 12:21:13 CDT 2018: Modified background signal; performing peak calling
Thu Apr 19 12:21:13 CDT 2018: MACS2 TEXT OUTPUT INCOMING
INFO  @ Thu, 19 Apr 2018 12:21:14: Read and build treatment bedGraph... 
INFO  @ Thu, 19 Apr 2018 12:21:18: Read and build control bedGraph... 
INFO  @ Thu, 19 Apr 2018 12:21:21: Build scoreTrackII... 
INFO  @ Thu, 19 Apr 2018 12:21:24: Calculate scores comparing treatment and control by 'qpois'... 
INFO  @ Thu, 19 Apr 2018 12:21:27: Write bedGraph of scores... 
INFO  @ Thu, 19 Apr 2018 12:21:36: Finished 'qpois'! Please check 'Control_HDAC_SMC3_HiChIPPeaks_EACH-SELF/hichipper_qvalue.bdg.tmp'! 
INFO  @ Thu, 19 Apr 2018 12:21:36: Read and build bedGraph... 
INFO  @ Thu, 19 Apr 2018 12:21:41: Call peaks from bedGraph... 
INFO  @ Thu, 19 Apr 2018 12:21:41: Write peaks... 
INFO  @ Thu, 19 Apr 2018 12:21:41: Done 
Thu Apr 19 12:33:54 CDT 2018: Performing hichipper-modified background peak calling
Read 7227576 rows and 6 (of 6) columns from 0.297 GB file in 00:00:09
Read 66417984 rows and 4 (of 4) columns from 1.984 GB file in 00:00:19
Read 36695775 rows and 4 (of 4) columns from 1.095 GB file in 00:00:10
Thu Apr 19 12:45:56 CDT 2018: Modified background signal; performing peak calling
Thu Apr 19 12:45:56 CDT 2018: MACS2 TEXT OUTPUT INCOMING
INFO  @ Thu, 19 Apr 2018 12:45:57: Read and build treatment bedGraph... 
INFO  @ Thu, 19 Apr 2018 12:46:59: Read and build control bedGraph... 
INFO  @ Thu, 19 Apr 2018 12:47:32: Build scoreTrackII... 
INFO  @ Thu, 19 Apr 2018 12:48:02: Calculate scores comparing treatment and control by 'qpois'... 
INFO  @ Thu, 19 Apr 2018 12:48:52: Write bedGraph of scores... 
INFO  @ Thu, 19 Apr 2018 12:50:01: Finished 'qpois'! Please check 'Control_HDAC_SMC3_HiChIPPeaks_EACH-SELF/hichipper_qvalue.bdg.tmp'! 
INFO  @ Thu, 19 Apr 2018 12:50:03: Read and build bedGraph... 
INFO  @ Thu, 19 Apr 2018 12:50:35: Call peaks from bedGraph... 
INFO  @ Thu, 19 Apr 2018 12:50:37: Write peaks... 
INFO  @ Thu, 19 Apr 2018 12:50:38: Done 
Read 7227576 rows and 6 (of 6) columns from 0.297 GB file in 00:00:09
Anchors removed due to excessive size (likely at ends of chromosomes): 15 
Read 7227576 rows and 6 (of 6) columns from 0.297 GB file in 00:00:09
Anchors removed due to excessive size (likely at ends of chromosomes): 5 
Thu Apr 19 12:51:25 CDT 2018: Processing Control_SMC3
Thu Apr 19 12:51:25 CDT 2018: Total_PETs=48274000
Thu Apr 19 12:53:20 CDT 2018: Mapped_unique_quality_pairs=70637958
Thu Apr 19 12:54:06 CDT 2018: Mapped_unique_quality_valid_pairs=33255507
Thu Apr 19 12:54:06 CDT 2018: Intersecting PETs with anchors
Thu Apr 19 12:54:12 CDT 2018: Finished the anchor merging.
Thu Apr 19 13:14:28 CDT 2018: Intrachromosomal_valid_small=3680202
Thu Apr 19 13:15:50 CDT 2018: Intrachromosomal_valid_med=17558449
Thu Apr 19 13:17:05 CDT 2018: Intrachromosomal_valid_large=5866650
Thu Apr 19 13:17:05 CDT 2018: Total number of anchors used: 631
Thu Apr 19 13:17:05 CDT 2018: Total number of reads in anchors: 262409
Thu Apr 19 13:21:05 CDT 2018: Mapped_unique_intra_quality_anchor=4647
Thu Apr 19 13:21:05 CDT 2018: Mapped_unique_intra_quality_anchor_small=2357
Thu Apr 19 13:21:05 CDT 2018: Mapped_unique_intra_quality_anchor_med=2286
Thu Apr 19 13:21:05 CDT 2018: Mapped_unique_intra_quality_anchor_large=4
Thu Apr 19 13:21:05 CDT 2018: Loop_PETs=2286
Thu Apr 19 13:21:05 CDT 2018: Processing HDAC_SMC3
Thu Apr 19 13:21:05 CDT 2018: Total_PETs=111263839
Thu Apr 19 13:24:30 CDT 2018: Mapped_unique_quality_pairs=125986837
Thu Apr 19 13:25:27 CDT 2018: Mapped_unique_quality_valid_pairs=33680149
Thu Apr 19 13:25:27 CDT 2018: Intersecting PETs with anchors
Thu Apr 19 13:25:32 CDT 2018: Finished the anchor merging.
Thu Apr 19 13:57:17 CDT 2018: Intrachromosomal_valid_small=16987842
Thu Apr 19 13:58:37 CDT 2018: Intrachromosomal_valid_med=9413688
Thu Apr 19 13:59:52 CDT 2018: Intrachromosomal_valid_large=2993967
Thu Apr 19 13:59:52 CDT 2018: Total number of anchors used: 78069
Thu Apr 19 13:59:52 CDT 2018: Total number of reads in anchors: 38007868
Thu Apr 19 14:05:35 CDT 2018: Mapped_unique_intra_quality_anchor=2128503
Thu Apr 19 14:05:35 CDT 2018: Mapped_unique_intra_quality_anchor_small=1751571
Thu Apr 19 14:05:35 CDT 2018: Mapped_unique_intra_quality_anchor_med=305072
Thu Apr 19 14:05:35 CDT 2018: Mapped_unique_intra_quality_anchor_large=71861
Thu Apr 19 14:05:39 CDT 2018: Loop_PETs=305072
Thu Apr 19 14:05:39 CDT 2018: 
['Rscript', u'Control_HDAC_SMC3_HiChIPPeaks_EACH-SELF/qcReport.R', '/Library/Python/2.7/site-packages/hichipper', 'Control_HDAC_SMC3_HiChIPPeaks_EACH-SELF', '/Volumes/Terranova2/HDAC_2_3-25-16/HiC_Pro_Test_3_03-16-18', '0.7.1', 'Control_SMC3 HDAC_SMC3']
/Volumes/Terranova2/HDAC_2_3-25-16/HiC_Pro_Test_3_03-16-18Using count as value column: use value.var to override.
Processing: Control_SMC3HDAC_SMC3
Error in { : task 1 failed - "need at least four unique 'x' values"
Calls: %do% -> <Anonymous>
Execution halted

Thanks for you help!!

**Comment by caleblareau** [comment]
Hi @cjt5 thanks for the comment. Could you post your `*.stat` files in a zipped file?

For what it's worth, the run does look successful, but the QC report appears to have failed from the error that you've given.

**Comment by cjt5** [comment]
Sure no problem. And thanks for the prompt response! 

My main concern is the Total number of anchors used: 631 in the Control_SMC3 condition. As the peak numbers in all the above mentioned cases are very high.

[Control_SMC3.stat.zip](https://github.com/aryeelab/hichipper/files/1929548/Control_SMC3.stat.zip)
[HDAC_SMC3.stat.zip](https://github.com/aryeelab/hichipper/files/1929549/HDAC_SMC3.stat.zip)

**Comment by caleblareau** [comment]
Yeah so I can't immediately pin-point the error, but I think what is happening is that the super small number of loops is causing an error when making the distribution in the QC report. Given that you've successfully run the tool with other anchor configurations, I would suggest to stick to those. You apparently have such little self-ligation reads that peak calling with just those doesn't seem sensible...

**Comment by cjt5** [comment]
Sorry for the hassle but one last question...as there were such high peak numbers in that condition when calling with other methods (i.e. ~80, 000 with COMBINED,SELF) does that mean the experiment is OK in your opinion? I am just rather new to HiChIP and want to be sure we are starting out properly.

Thanks again!
Best!

**Comment by caleblareau** [comment]
Unlike say ChIP-seq where peak # is a good proxy for library quality, we really don't seem to think that ordinal peak #s is an appropriate measure for library quality. The single best metric, in our view, is the % of long range interactions, which typically is around or above 15% for high quality libraries. This number is in the first table in the hichipper qc report.

**Comment by cjt5** [comment]
Ok great! Thanks very much!!
