### ISSUE TITLE
Error in .Call2("NCList_find_overlaps_in_groups", start(q), end(q), q_space

### ISSUE THREAD

**Issue by dongxiaota** [aryeelab/hichipper#41]
I run the test data by (nohup hichipper --out output2 yaml/example_EACH_ALL.yaml &) ,but get the below erros:
Wed May 30 10:10:39 CST 2018: Starting hichipper pipeline v0.7.0
Wed May 30 10:10:39 CST 2018: Parsing user parameters
Wed May 30 10:10:47 CST 2018: Performing hichipper-modified background peak calling
Error in .Call2("NCList_find_overlaps_in_groups", start(q), end(q), q_space,  : 
  when 'type' is "any", at least one of 'maxgap' and 'minoverlap' must be set to its default value
Calls: computeRatioEtc ... findOverlaps_GNCList -> <Anonymous> -> .Call2 -> .Call
Execution halted

**Comment by caleblareau** [comment]
Likely something related to this:
https://support.bioconductor.org/p/84239/

@dongxiaota maybe try updating R && dependency packages?

**Comment by dongxiaota** [comment]
ok,thanks!
