### ISSUE TITLE
Add option to keep temporary files

### ISSUE THREAD

**Issue by afrendeiro** [aryeelab/hichipper#42]
Thanks for developing the software!
Would be nice to have an option not to remove temporary files - especially the R scripts.
This would help debugging during the first runs.

**Comment by caleblareau** [comment]
Thanks @afrendeiro 

This actually does exist already... see
http://hichipper.readthedocs.io/en/latest/content/Configuration.html

```
--keep-temp-files
```

**Comment by afrendeiro** [comment]
Ah, my bad I could swear it wasn't there. Thanks anyway!

**Comment by caleblareau** [comment]
no problem! it's been known to happen to me as well :)
