### ISSUE TITLE
question about error message

### ISSUE THREAD

**Issue by jakeukleja** [aryeelab/hichipper#45]
Hello! I had a question regrading running hichipper

Fri Jun 22 16:00:24 EDT 2018: Starting hichipper pipeline v0.7.3
Fri Jun 22 16:00:24 EDT 2018: Parsing user parameters
Fri Jun 22 16:00:24 EDT 2018: .yaml file detected
ls: cannot access hicpro/bowtie_results/bwt2/mcd1_rep1/*.pairstat: No such file or directory

The name of my files, I have show below. It seems I don't have the pairstat file, but this is the output I obtained from the HiCPro. Can I use these files? The output contained:

In a directory called mcd1_rep1:
DB-1_R1_001_hg19.bwt2glob.bam                  
DB-1_R2_001_hg19.bwt2glob.bam
DB-1_R1_001_hg19.bwt2glob.unmap_trimmed.fastq  
DB-1_R2_001_hg19.bwt2glob.unmap.fastq

Am I missing files?

**Comment by caleblareau** [comment]
1) What version of HiC-Pro are you using?
2) How did you execute HiC-Pro? If you use the `-p` mode, then it generally works in my experience.

**Comment by uklejaj** [comment]
This issue seems to have resolved itself. It was an issue in file transfer actually. Thank you.
