### ISSUE TITLE
Error in { : task 1 failed - "incorrect number of dimensions" Calls: %do% -> <Anonymous> Execution halted

### ISSUE THREAD

**Issue by docdot** [aryeelab/hichipper#49]
To whom it may concern,

I'm receiving the following error:

`
Error in { : task 1 failed - "incorrect number of dimensions"
Calls: %do% -> <Anonymous>
Execution halted
`

All dependencies were installed. I'm using MACOS High Sierra. 
Any idea what could be?

Many thanks,

Raphael

**Comment by caleblareau** [comment]
hmmm a bit non-specific of an error message. My guess would be the number of peaks that were called was close to zero, and hence we got relatively few loops. Can you `ls -lrtR` the output directory?
