### ISSUE TITLE
--make-ucsc flag error

### ISSUE THREAD

**Issue by docdot** [aryeelab/hichipper#50]
To whom it may concern,

I'm receiving the following message when I use the flag --make-ucsc.

`
Fri Aug 17 12:45:29 CEST 2018: Starting hichipper pipeline v0.7.3
Fri Aug 17 12:45:29 CEST 2018: Parsing user parameters
Fri Aug 17 12:45:29 CEST 2018: .yaml file detected
ERROR: Could not import any samples from the user specification; check flags, logs and .yaml configuration; quitting
`

-I have htslib and tabix (together with samtools) installed. 

-My .yaml file works without the --make-ucsc flag

`
peaks:
  - EACH,ALL
resfrags:
  - /Users/raphael/Desktop/Bioinformatic/test/hg19_MboI_resfrag.bed
hicpro_output:
  - /Users/raphael/Desktop/Bioinformatic/test/HiChIP_HiCPro_output

`

- I'm running one sample only

Any ideas what could the source of the error?

Many thanks

**Comment by caleblareau** [comment]
hmm can you verify `which bgzip` and `which tabix` give you something?

**Comment by docdot** [comment]
Tabix was missing.
I installed and now is appearing another error: 
'
home:~/Desktop/Software/HiChipper$ hichipper --out HiChIP config.yaml --make-ucsc
Thu Oct 11 13:42:06 CEST 2018: Starting hichipper pipeline v0.7.3
Thu Oct 11 13:42:06 CEST 2018: Parsing user parameters
Thu Oct 11 13:42:06 CEST 2018: .yaml file detected
Thu Oct 11 13:42:12 CEST 2018: Performing hichipper-modified background peak calling
Error: could not find function "endsWith"
Execution halted
Thu Oct 11 13:42:17 CEST 2018: Modified background signal; performing peak calling
Thu Oct 11 13:42:17 CEST 2018: MACS2 TEXT OUTPUT INCOMING
INFO  @ Thu, 11 Oct 2018 13:42:17: Read and build treatment bedGraph... 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 617, in <module>
    main()
  File "/usr/local/bin/macs2", line 73, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/bdgcmp_cmd.py", line 40, in run
    tbtrack = tbio.build_bdgtrack()
  File "MACS2/IO/BedGraphIO.pyx", line 97, in MACS2.IO.BedGraphIO.bedGraphIO.build_bdgtrack (MACS2/IO/BedGraphIO.c:1079)
IOError: [Errno 2] No such file or directory: 'HiChIP/adjustedTreatment.bdg.tmp'
INFO  @ Thu, 11 Oct 2018 13:42:17: Read and build bedGraph... 
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 617, in <module>
    main()
  File "/usr/local/bin/macs2", line 65, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/bdgpeakcall_cmd.py", line 51, in run
    btrack = bio.build_bdgtrack(baseline_value=0)
  File "MACS2/IO/BedGraphIO.pyx", line 97, in MACS2.IO.BedGraphIO.bedGraphIO.build_bdgtrack (MACS2/IO/BedGraphIO.c:1079)
IOError: [Errno 2] No such file or directory: 'HiChIP/hichipper_qvalue.bdg.tmp'
mv: cannot stat 'HiChIP/hichipper_peaks.bed': No such file or directory
awk: fatal: cannot open file 'HiChIP/allSamples_temporary_hichipperPeaks.bed' for reading (No such file or directory)
Error: could not find function "endsWith"
Execution halted
Do 11. Okt 13:42:22 CEST 2018: Processing HiC_input
Do 11. Okt 13:42:22 CEST 2018: Total_PETs=3375114
Do 11. Okt 13:42:22 CEST 2018: Mapped_unique_quality_pairs=2012134
Do 11. Okt 13:42:22 CEST 2018: Mapped_unique_quality_valid_pairs=892189
Do 11. Okt 13:42:22 CEST 2018: Intersecting PETs with anchors
Error: The requested file (HiChIP/allSamples_temporary_hichipperPeaks.bed_pad.bed.tmprf.tmp) could not be opened. Error message: (No such file or directory). Exiting!
/usr/local/lib/python2.7/dist-packages/hichipper/interactionsCall.sh: line 36: --keep-temp-files: command not found
Do 11. Okt 13:42:22 CEST 2018: Something went wrong in determining peaks for anchor inference; rerun with the  flag to debug.
ERROR: something failed at the individual sample level; check the .log file for more info
'

Thanks,

Raphael

**Comment by woshiyangsi** [comment]
Hi @vidaletal ，

Do you solve the problem? I meet the same error with you.

Error: The requested file (HiChIP/allSamples_temporary_hichipperPeaks.bed_pad.bed.tmprf.tmp) could not be opened. Error message: (No such file or directory). Exiting!
/usr/local/lib/python2.7/dist-packages/hichipper/interactionsCall.sh: line 36: --keep-temp-files: command not found
Do 11. Okt 13:42:22 CEST 2018: Something went wrong in determining peaks for anchor inference; rerun with the  flag to debug.
ERROR: something failed at the individual sample level; check the .log file for more info

looking forward your reply!

Thanks,
Siyu
