### ISSUE TITLE
About the pre processing / RM_DUP = 0

### ISSUE THREAD

**Issue by docdot** [aryeelab/hichipper#56]
Dear Caleb,

I've started working with Hi-ChIP quite recently and I was wondering if it wouldn't make more sense to keep the duplicates of Hi-ChIP samples in the pre-processing of HiC-Pro.  The reads from Hi-ChIP are expected to overlap, decreasing the library complexity as it is expected in ChIP-seq. Even more than ChIP-seq as it has the biotin pulldown as well. In this sense, wouldn't these reads represent exactly what we were looking for: an enrichment?

In code terms, shouldn't we:
```
#######################################################################
## Hi-C processing
#######################################################################
MIN_CIS_DIST =
GET_ALL_INTERACTION_CLASSES = 1
GET_PROCESS_SAM = 1
RM_SINGLETON = 1
RM_MULTI = 1
RM_DUP = 0
```

Please correct me if wrong.

Best

Raphael

**Comment by docdot** [comment]
Hi Caleb,

Many thanks for your feedback. I'm observing this in all my dataset.  
Would you mind provide the .validPairs of the sample dSRR3467177 in hichipper/tests/hicpro/hic_results/data/dSRR3467177/?
I'd like to compare with my own dataset after keeping the duplicates.

Many thanks,

Raphael

**Comment by caleblareau** [comment]
Do these files work?

https://github.com/aryeelab/hichipper/tree/master/tests/hicpro/hic_results/data/dSRR3467177

**Comment by docdot** [comment]
Many thanks, 

Just to double check, have you kept the duplicates in these files during the analysis?
