### ISSUE TITLE
chip-seq input question of Hichipper

### ISSUE THREAD

**Issue by skytguuu** [aryeelab/hichipper#67]
Hi，
Recently I tried to use Hichipper to analyze my Hichip data. I had successfully finished the HiC-Pro part. However, when I try to make .yaml file and it includes " peaks" file, but I did not have any chip-seq data. So, can it work well without peaks? How can I get the peaks file from my hichip experiment?

Thanks

**Comment by caleblareau** [comment]
You can used the logic of DATA,FRAGMENT_TYPE e.g. COMBINED,SELF 

see https://hichipper.readthedocs.io/en/latest/content/Peaks.html
