### ISSUE TITLE
Parameters questions

### ISSUE THREAD

**Issue by skytguuu** [aryeelab/hichipper#71]
Hi,
Recently, I tried to use hichipper to analyze HiChIP data. However, I was confused to some paramters.
1. '--min-dist'  is defined the minimum distance (default = 5000), so I am wondering whether it is related with the resolution of my HiChIP data. For example, in situ HiC, the max resulotion is 20kb, could it also be set with the default parameter (5kb)?

2.'--macs2-string' is used the macs2 default parameters (-q 0.01 --extsize 147 --nomodel). If I want to change it, should I just use '--macs2-string -q 0.05 --extsize 150 --nomodel' ? Because the reads fragment is always enriched at 300-500bp, so should I change the '--extsize' to 150?

3. '--peak-pad' and '--merge-gap' : whether this paramenter is related with the enzyme restriction sites? If I use HindIII or less enzyme sites in genome, should I change the peak padding width?

4.'--read-length': I don't know what's the function of this parameter? What will happen if I set longer or short of read length 

I am appreciated for your explanation.
Thanks

**Comment by caleblareau** [comment]
1) It is related but not necessarily the same thing. Also, I don't think that in situ Hi-C has a defined resolution except for how deep you sequence... here they achieve 1kb https://www.ncbi.nlm.nih.gov/pubmed/25497547. Do you have a reference as to why this should be changed? I don't see an immediate need as one can also post-hoc filter these. The minimum width was more from ChIA-PET style analyses where 5kb has generally been considered the resolution that one can resolve interactions. 

2) Yes, your recommendation seems right.

3) Please see our supplement (https://www.nature.com/articles/nmeth.4583) for descriptions of these parameters. I don't have explicit experience with HindIII (6 cutter) but I would think that you could decrease the peak-pad parameter if you wanted. The defaults should also be fine?

4) You should leave this as the value that is as close to the length of the read that you sequenced. It's used for the final overlap counting.

**Comment by skytguuu** [comment]
Thanks for your explanation. 
According to the same paper (Rao et al, Cell, 2014), it defined the max resolution is that the smallest locus size such that 80% of loci should have at least 1000 contacts. But it seems your are right, it is related but not the same thing.
Thanks for your help. BTW, I am also confused to the qc reports. How can I say a hichip experiment is good or bad?

Thanks!
Best

**Comment by caleblareau** [comment]
Our best metric is “% Pets in long range interactions” which should be around or above 10% in a good library. I’ve documented several such instances of good libraries here: http://aryee.mgh.harvard.edu/hichipper/qcReports/ <http://aryee.mgh.harvard.edu/hichipper/qcReports/>

(e.g. See 3rd number in the top column here- http://aryee.mgh.harvard.edu/hichipper/qcReports/Good/NatureGenetics/GM12878_H3K27ac.hichipper.qcreport.html <http://aryee.mgh.harvard.edu/hichipper/qcReports/Good/NatureGenetics/GM12878_H3K27ac.hichipper.qcreport.html>)

**Comment by skytguuu** [comment]
I am appreciated for your help.

Thanks,
Best
