### ISSUE TITLE
ERROR: Missing hic_results or bowtie_results files for H446-rep

### ISSUE THREAD

**Issue by jlpulice** [aryeelab/hichipper#73]
HI!

I'm getting this error: ERROR: Missing hic_results or bowtie_results files for H446-rep; either exclude the sample or manage the file architecture/input

Under 
hicpro-output/bowtie_results/bwt2/H446-rep/:
H446-rep_hg19.bwt2pairs.bam  H446-rep_hg19.bwt2pairs.pairstat  H446-rep_R1_hg19.bwt2merged.bam  H446-rep_R1_hg19.mapstat  H446-rep_R2_hg19.bwt2merged.bam  H446-rep_R2_hg19.mapstat

hicpro-output1/hic_results/data/H446-rep/:
H446-rep_hg19.bwt2pairs.DEPairs    H446-rep_hg19.bwt2pairs.FiltPairs        H446-rep_hg19.bwt2pairs.REPairs  H446-rep_hg19.bwt2pairs.SCPairs      H446-rep_hg19.bwt2pairs.validPairs
H446-rep_hg19.bwt2pairs.DumpPairs  H446-rep_hg19.bwt2pairs_interaction.bam  H446-rep_hg19.bwt2pairs.RSstat   H446-rep_hg19.bwt2pairs.SinglePairs

Other directories have identical files and aren't throwing this error, and I can't trace back what file is missing.

I am using hichipper v0.7.7

**Comment by caleblareau** [comment]
did you run step 2 of HiC-Pro (assuming you ran in parallel mode) and the hichipper command? I think it's the _allValidPairs file that is missing

**Comment by jlpulice** [comment]
Yep that was it all set. Thanks!
